version: '3.8'

services:
  backend:
    build: ./backend
    container_name: rag_backend
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/app/chroma_db
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - VECTORSTORE_PATH=/app/chroma_db
      - IMBEDDING_MODEL_NAME=BAAI/bge-large-en
      - OLLAMA_MODEL=llama3
      - RERANKER_MODEL_NAME=cross-encoder/ms-marco-MiniLM-L-6-v2
      - WHISPER_MODEL_SIZE=medium
    networks:
      - rag_network

  frontend:
    build: ./frontend
    container_name: rag_frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
      - STREAMLIT_SERVER_PORT=8501
    depends_on:
      - backend
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge